
name: get input test
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

     - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' 
          
      - name: fetch duncan's input 
        env:
          DUNCAN_COOKIE: ${{ secrets.DUNCAN_COOKIE }}
        run: python Duncan/getinputduncantest.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "added daily puzzle inputs" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
