name: Update README ⭐
on:
  schedule:
    - cron: "*/14 * * * *"  # Every 15 minutes
  workflow_dispatch:

jobs:
  update-readmed:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: 2305618
          sessionCookie: ${{ secrets.DUNCAN_COOKIE}}
          tableMarker:  <!--aoc-stars-duncan-->
          year: 2023
      - uses: stefanzweifel/git-auto-commit-action@v5 # use v5
        with:
           commit_message: Update README stars

  update-readmea:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: 2305618
          sessionCookie: ${{ secrets.AMIR_COOKIE}}
          tableMarker: <!--aoc-stars-amir-->
          year: 2023
      - uses: stefanzweifel/git-auto-commit-action@v5 # use v5
        with:
          commit_message: Update README stars